- Entertaiment:
    - Jellyfin:
        icon: jellyfin.png
        href: http://steel.fmn.com/jellyfin
        description: Media streaming
        widget:
          type: jellyfin
          url: http://steel.fmn.com/jellyfin
          key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
    - Immich:
        icon: immich.png
        href: http://steel.fmn.com/immich
        descritption: Photo storage
        widget:
          type: immich
          url: http://steel.fmn.com/immich
          key: {{HOMEPAGE_VAR_IMMICH_KEY}}
          version: 2 # optional, default is 1
- Utility:
    - Torrents:
        icon: transmission.png
        href: http://steel.fmn.com/transmission
        description: Transmission torrent client
        widget:
          type: transmission
          url: http://steel.fmn.com/transmission/rpc
          username: {HOMEPAGE_VAR_TRANSMISSION_RPC_USERNAME}
          password: {HOMEPAGE_VAR_TRANSMISSION_RPC_PASSWORD}
- Management:
    - Portainer:
        icon: portainer.png
        href: http://steel.fmn.com/portainer
        description: Container management
        widget:
          type: portainer
          url: http://steel.fmn.com/portainer
          env: 3
          key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
